print("Calculate fuel consumption.")
Distance = int(input("Enter travel distance (kilometers): "))
Feed = input("Enter fuel usage (liters): ")
Consumption = int(Feed) / (Distance / 100)
print(f"Fuel consumption is {round(Consumption, 2)}l/100km")