print("Calculate the area of a wall.")
W = input("Enter the width in meters: ").replace(",",".")
H = input("Enter the height in meters: ").replace(",",".")
print(f"Width is {W}m and height is {H}m.")
print(f"The wall will be {round(float(W) * float(H), 2)} square meters.")